site_url: https://sonjajosipovic.se/
locale: 'sv'

backend:
  name: git-gateway
  branch: main

media_folder: '/src/cms/uploads/'
public_folder: '/public/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    create: true
    folder: '/src/blog/_posts'
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Category', name: 'category', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Language', name: 'language', default: 'sv', widget: 'hidden' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
          media_library: { max_file_size: 1012000 },
        }
      - {
          label: 'Gallery',
          name: 'galleryImages',
          widget: 'list',
          summary: 'Gallery',
          field:
            {
              label: 'Image',
              name: 'image',
              widget: 'object',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Alt Text', name: 'alt', widget: 'string', required: false },
                ],
            },
        }
